# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PrintSelection
                                 A QGIS plugin
 Outputs selected features ordered by layer to text console.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-30
        copyright            : (C) 2024 by Andreas Steffens (Geo Daten Service GmbH)
        email                : a.steffens@gds-team.de
 ***************************************************************************/

 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Andreas Steffens'
__date__ = '30/7/2024'
__copyright__ = 'Copyright 2024, Andreas Steffens (GDS Geo Daten Service GmbH)'

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PrintSelection class from file print_selection.py.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .print_selection import PrintSelection
    return PrintSelection(iface)
